## Week 4

### Defining Functions

In [ ]:
def my_function(input_string):
    print('This is the function printing:', input_string)
    return input_string + ': this is the returned value'

print(my_function('A string'))

This is the function printing: A string
A string: this is the returned value


The function above has these parts:
- definition statement: def + the name of the function + any number of arguments/parameters taken in by the function
    - The arguments/parameters are the variables that will be used by the function, and make it so that you can run the function with different input values
- the action: in this case it is a simple print call, but you can make the action as complex as you need
- the return statement: this identifies the value that will be output by the function
    - any variables defined within a function will not be available outside the function - only the returned variable will be output. 
    

Here's a more complex example:

In [ ]:
def my_other_function(x, y, list_of_ints):
    num_list = []
    for i in list_of_ints:
        num = x + y*i
        num_list.append(num)
    return num_list

output_value = my_other_function(2, 3, [4,5,6])
print(output_value)
    
    

[14, 17, 20]


- This function takes in three arguments: `x`, a number, `y`, another number, and `list_of_ints`, a list of integers. 
- an empty list, `num_list`, is defined, which will be a place to store the values the function generates
- a for-loop takes each value in the `list_of_ints` and includes them in the equation `x + y*(current_variable_in_list_of_ints)`, and assigns that value to the variable `num`
- `num` is the added to the list `num_list`
- the function returns `num_list` so that when the function is called and assigned to `output_value`, the variable `output_value` now contains the returned `num_list` from `my_other_function`


### Nested for-loops
If you write a for-loop within another for-loop, the interior for-loop will run fully each time the exterior for-loop iterates:

In [ ]:
my_list = ['alpha', 'bravo', 'charlie']
for list_val in my_list:
    print(list_val)

alpha
bravo
charlie


In [ ]:
my_list = ['alpha', 'bravo', 'charlie']
for list_val in my_list:
    print(list_val)
    for letter in list_val:
        print(letter)

alpha
a
l
p
h
a
bravo
b
r
a
v
o
charlie
c
h
a
r
l
i
e


### Logical Operators

- >, <, >=, <=, == (is equal), != (is not equal)
- These operators can be used to compare various objects
- The output of a logical operation is a Boolean value (`True` or `False`)


In [ ]:
print(5>3)
print(5<3)

True
False


In [ ]:
string1 = 'alpha'
string2 = 'kilo'
string3 = 'alpha'
string4 = 'alpaca'

print(string1 < string2) # when > or < are used to compare strings, they evaluate alphabetical order

print(string3 < string4)

print(string1 == string3)

print(string1 != string2)

True
False
True
True


- Using a logical operator to compare two arrays will return another array of the same shape containing Boolean values.
    - Each element of the first array will be compared to the corresponding element of the second array

In [ ]:
import numpy as np
array1 = np.array([1,1,2,3,5,8])
array2 = np.array([4,6,6,1,9,8])

comparison_array = array1 > array2
comparison_array

array([False, False, False,  True, False, False])

In [ ]:
array_2D_1 = np.array([[1,1,2,3,5,8],[4,6,6,1,9,8]])
array_2D_2 = np.array([[5,4,2,7,3,4],[5,3,1,2,9,8]])

comparison_array_2D =  array_2D_1 == array_2D_2
comparison_array_2D

array([[False, False,  True, False, False, False],
       [False, False, False, False,  True,  True]])

By applying a Boolean array to another array, you select for True values:

In [ ]:
array_2D_1 = np.array([[1,1,2,3,5,8],[4,6,6,1,9,8]])
array_2D_2 = np.array([[5,4,2,7,3,4],[5,3,1,2,9,8]])

comparison_array_2D =  array_2D_1 == array_2D_2

output_array = array_2D_1[comparison_array_2D]

print("Original:\n",array_2D_1)
print("Comparison:\n",comparison_array_2D)
print("Output:\n",output_array) # This 'applies' the Boolean array to the original array, returning only the
                                # values that correspond to "True" in comparison_array_2D


Original:
 [[1 1 2 3 5 8]
 [4 6 6 1 9 8]]
Comparison:
 [[False False  True False False False]
 [False False False False  True  True]]
Output:
 [2 9 8]


### If/else-statements:
Use logical operators inside an if-statement to perform an action if a condition is met:

In [ ]:
x = 7
if x > 5:
    print("X is greater than five")

X is greater than five


Add an `else` condition to specify what happens if the condition is not met:

In [ ]:
x = 3
if x > 5:
    print("X is greater than five")
else:
    print("X is not greater than five")

X is not greater than five


### in statements:
- Evaluate whether an element is in an object

In [ ]:
letter = 'a'
string_list = ['alpha', 'kilo']

for string in string_list:
    if letter in string:
        print(string,"contains an",letter)
    else:
        print(string,"has no",letter)

alpha contains an a
kilo has no a


In [ ]:
num_list = [0,4,6,1,2]
print(4 in num_list)
print(3 in num_list)

True
False
