## Week 3

- Read in data from a .csv file (comma separated variables)

`import numpy as np`<br>
`data = np.loadtxt('path_to_csv/csv_name.csv', delimiter = ',')`

### Generate heatmap:

`import matplotlib.pyplot as plt`<br>
`plt.imshow(data)`<br>
`plt.colorbar()`<br>
`plt.ylabel('y label')`<br>
`plt.xlabel('x label')`<br>

### np.arange(x,y,z)
Produces a range from value x up to but not including y, counting by z



In [ ]:
import numpy as np
print(np.arange(2,15))
print(np.arange(0,10,2))
print(np.arange(5,1,-1))


[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 2 4 6 8]
[5 4 3 2]


### np.mean()
Takes the mean of an array or across the rows or column
`np.mean(array)` returns the mean of all values in the array
`np.mean(array, axis = 0)` takes the mean of each column
`np.mean(array, axis = 1)` takes the mean of each row

Note: don't forget to check the shape of your output array to be sure you took the mean of the dimension you wanted.

**np.max()**, **np.min()**, and **np.sum()** function in the same way

### np.zeros(n), np.ones(n)

Create an array of zeros or ones of length n

In [ ]:
import numpy as np

print(np.zeros(7))
print(np.ones(5))
print(np.ones(5)+3)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[4. 4. 4. 4. 4.]


### Plotting: Scatter plots, etc.

- Create a scatter plot: <br><br>
    `plt.scatter(x, y, color = , marker = , etc.)`<br><br>

### For-loops
Structure:<br>
`for <variable> in <iterable object>:`<br>
`    do action`

Anything indented will be contained in the loop


In [ ]:
odds=[1,3,5,7]    # Define list (iterable)
for num in odds:  # For each variable (called num) in odds, do:
    print(num)    # Action (print the variable)

1
3
5
7


In [ ]:
odds=[1,3,5,7]    
for anything in odds:  # the iterable variable can be called anything you want
    print(anything) 

1
3
5
7


In [ ]:
odds=[1,3,5,7]    
for num in odds:  
    print('loop')   # The action doesn't need to necessarily use the variable.
                    # in this case, the action (print('loop')) is performed as many times as there are variables in the list

loop
loop
loop
loop


### Appending to lists:
  



In [ ]:
odds=[1,3,5,7]    
more_odds = odds + [9]
print(more_odds)

[1, 3, 5, 7, 9]


In [ ]:
more_odds.append(11) # Note you don't have to assign more_odds.append() to a new variable, more_odds is automatically updated with .append()
print(more_odds)     # In fact, if you run this cell a few more times, it will continue to append 

[1, 3, 5, 7, 9, 11]


### Creating a counter for a for-loop:


In [ ]:
counter = 0
for i in range(0,5):
    print('loop ', counter)
    counter += 1              # This notation += is shorthand for "counter = counter + 1"
    

loop  0
loop  1
loop  2
loop  3
loop  4


### enumerate():

`enumerate()` automatically creates a counter by generating an 'enumerate object' of the format `[(0, item[0]), etc.]`

In [ ]:
my_list = ['alpha', 'bravo', 'charlie', 'delta', 'echo']
print(list(enumerate(my_list)))

[(0, 'alpha'), (1, 'bravo'), (2, 'charlie'), (3, 'delta'), (4, 'echo')]


You can assign the counter value and the list value to two variables so that they are both callable in the for-loop:


In [ ]:
for counter, list_value in enumerate(my_list):
    print(counter)
    print(list_value)

0
alpha
1
bravo
2
charlie
3
delta
4
echo
